# -*- coding: utf8 -*-

db_correctionbot = {
1 : ('symbspejok' , '(*)'), 
2 : ('symbspecrochetgauche' , '['), 
3 : ('symbspecrochetdroit' , ']'), 
4 : ('symbspeaccogauche' , '{'), 
5 : ('symbspeaccodroit' , '}'), 
6 : ('symbspesmileyaigu' , ':>'), 
7 : ('symbspeflechevardroit' , '<-'), 
8 : ('symbspeflechevargauche' , '->'), 
9 : ('symbspetilde' , '~'), 
10 : ('symbspebarre' , '|'), 
11 : ('symbspenoreut' , '<NOREUT>'), 
12 : ('symbchangecervdroit' , '<chgcerva:'), 
13 : ('symbsignesup' , '>'), 
14 : ('symbignorer' , '<IGNORER>')
}

db_correction = {
1 : ('?' , ' ?'), 
2 : ('!' , ' !'), 
3 : ('  ?' , ' ?'), 
4 : ('  !' , ' !'), 
5 : ('&quot;' , ''), 
6 : ('(*)' , 'symbspejok'), 
7 : ('[' , 'symbspecrochetgauche'), 
8 : (']' , 'symbspecrochetdroit'), 
9 : ('{' , 'symbspeaccogauche'), 
10 : ('}' , 'symbspeaccodroit'), 
11 : (':>' , 'symbspesmileyaigu'), 
12 : ('<-' , 'symbspeflechevardroit'), 
13 : ('->' , 'symbspeflechevargauche'), 
14 : ('~' , 'symbspetilde'), 
15 : ('|' , 'symbspebarre'), 
16 : ('<NOREUT>' , 'symbspenoreut'), 
17 : ('<chgcerva:' , 'symbchangecervdroit'), 
18 : ('>' , 'symbsignesup'), 
19 : ('<IGNORER>' , 'symbignorer'), 
20 : ('*' , 'symbetoile'), 
21 : ('c\'ets ' , 'c\'est'), 
22 : ('ej ' , ' je'), 
23 : ('koi' , 'quoi'), 
24 : ('ca av ' , 'ca va'), 
25 : ('ça av ' , 'ça va'), 
26 : ('t\'as' , 'tu as'), 
27 : ('es tu' , 'es-tu'), 
28 : ('t\'s ' , 'tu es'), 
29 : ('tu est ' , 'tu es'), 
30 : ('tu t\'es ' , 'tu tXX\'XXes'), 
31 : ('t\'es ' , 'tu es'), 
32 : ('tu tXX\'XXes ' , 'tu t\'es'), 
33 : ('t\'se ' , 'tu es'), 
34 : ('t\'es pas ' , 'tu n\'es pas'), 
35 : ('t\'est pas ' , 'tu n\'es pas'), 
36 : ('tu n\'est pas ' , 'tu n\'es pas'), 
37 : ('tu es pas' , 'tu n\'es pas'), 
38 : ('t\'iame' , 't\'aime'), 
39 : ('keske' , 'qu\'est-ce que'), 
40 : ('republique' , 'république'), 
41 : ('egypte' , 'égypte'), 
42 : ('je suis allé' , 'j\'ai été'), 
43 : ('c\'est quoi ton' , 'quel est ton'), 
44 : ('c\'est quoi ton' , 'quel est ton'), 
45 : ('c\'est quoi ta' , 'quel est ta'), 
46 : ('c\'est quoi tes' , 'quel sont tes'), 
47 : ('qu\'est-ce que tu veux' , 'que veux-tu'), 
48 : ('qu\'est ce qu' , 'Qu\'est-ce qu'), 
49 : ('veux tu' , 'veux-tu'), 
50 : ('repete ' , 'répète'), 
51 : ('répete ' , 'répète'), 
52 : ('répéte ' , 'répète'), 
53 : ('repéte ' , 'répète'), 
54 : ('repète ' , 'répète'), 
55 : ('rèpète ' , 'répète'), 
56 : ('répête ' , 'répète'), 
57 : ('repête ' , 'répète'), 
58 : ('rèpête ' , 'répète'), 
59 : ('repetes ' , 'répètes'), 
60 : ('répetes ' , 'répètes'), 
61 : ('répétes ' , 'répètes'), 
62 : ('repétes ' , 'répètes'), 
63 : ('repètes ' , 'répètes'), 
64 : ('rèpètes ' , 'répètes'), 
65 : ('répêtes ' , 'répètes'), 
66 : ('repêtes ' , 'répètes'), 
67 : ('rèpêtes ' , 'répètes'), 
68 : ('garcon' , 'garçon'), 
69 : ('ta geule' , 'ta gueule'), 
70 : ('desolé' , 'désolé'), 
71 : ('désole' , 'désolé'), 
72 : ('desole' , 'désolé'), 
73 : ('dsl' , 'désolé'), 
74 : ('carrement' , 'carrément'), 
75 : ('carément' , 'carrément'), 
76 : ('carement' , 'carrément'), 
77 : ('jte' , 'je te'), 
78 : ('jme' , 'je me'), 
79 : ('appele' , 'appelle'), 
80 : ('apele' , 'appelle'), 
81 : ('apelle' , 'appelle'), 
82 : ('apèle' , 'appelle'), 
83 : ('appèle' , 'appelle'), 
84 : ('appèlle' , 'appelle'), 
85 : ('m\'apel' , 'm\'appelle'), 
86 : ('tu t\'apel ' , 'tu t\'appelles'), 
87 : ('tu t\'appel ' , 'tu t\'appelles'), 
88 : ('me prénomme' , 'm\'appelle'), 
89 : ('me prénome' , 'm\'appelle'), 
90 : ('me prenome' , 'm\'appelle'), 
91 : ('me prénomme' , 'm\'appelle'), 
92 : ('je me nomme' , 'je m\'appelle'), 
93 : ('je me nome' , 'je m\'appelle'), 
94 : ('on me nomme' , 'je m\'appelle'), 
95 : ('on me nome' , 'je m\'appelle'), 
96 : ('nomme-moi' , 'je m\'appelle'), 
97 : ('nome-moi' , 'je m\'appelle'), 
98 : ('nomme moi' , 'je m\'appelle'), 
99 : ('nomemoi' , 'je m\'appelle'), 
100 : ('mon nom c\'est' , 'je m\'appelle'), 
101 : ('mon vrai nom c\'est' , 'je m\'appelle'), 
102 : ('mon nom est' , 'je m\'appelle'), 
103 : ('mon vrai nom est' , 'je m\'appelle'), 
104 : ('mon prénom est' , 'je m\'appelle'), 
105 : ('mon prenom est' , 'je m\'appelle'), 
106 : ('my name is' , 'je m\'appelle'), 
107 : ('je m\'appelle:' , 'je m\'appelle'), 
108 : ('je m\'appelle :' , 'je m\'appelle'), 
109 : ('debile' , 'débile'), 
110 : ('je vien ' , 'je viens'), 
111 : ('conard' , 'connard'), 
112 : ('\' ' , '\''), 
113 : ('je sais pas' , 'je ne sais pas'), 
114 : ('je suis pas' , 'je ne suis pas'), 
115 : ('c\'etait' , 'c\'était'), 
116 : ('je me sens' , 'je suis'), 
117 : ('je me trouve' , 'je suis'), 
118 : ('la guele' , 'la gueule'), 
119 : ('discute' , 'parle'), 
120 : ('embete' , 'embête'), 
121 : ('embéte' , 'embête'), 
122 : ('embète' , 'embête'), 
123 : ('memoire' , 'mémoire'), 
124 : ('quelqu un' , 'quelqu\'un'), 
125 : ('qu\'est ce tu' , 'qu\'est-ce que tu'), 
126 : ('aleatoire' , 'aléatoire'), 
127 : ('sais tu ' , 'sais-tu'), 
128 : ('peux tu' , 'peux-tu'), 
129 : ('as tu' , 'as-tu'), 
130 : ('qu\'est ce que tu sais' , 'que sais-tu'), 
131 : ('que peux tu me dire sur' , 'que sais-tu sur'), 
132 : ('que peux tu dire sur' , 'que sais-tu sur'), 
133 : ('que peux-tu dire sur' , 'que sais-tu sur'), 
134 : ('que peux-tu me dire sur' , 'que sais-tu sur'), 
135 : ('que tu peux me dire sur' , 'que sais-tu sur'), 
136 : ('que sais-tu sur moi' , 'que sais-tu de moi'), 
137 : ('que sais tu sur moi' , 'que sais-tu de moi'), 
138 : ('programe' , 'programme'), 
139 : ('est elle' , 'est-elle'), 
140 : ('casserolle' , 'casserole'), 
141 : ('deranger' , 'déranger'), 
142 : ('prenom' , 'prénom'), 
143 : ('repond' , 'répond'), 
144 : ('réponds moi' , 'réponds-moi'), 
145 : ('reponds moi' , 'réponds-moi'), 
146 : ('répond moi' , 'réponds-moi'), 
147 : ('repond moi' , 'réponds-moi'), 
148 : ('puis-je avoir ton' , 'quel est ton'), 
149 : ('puis je avoir ton' , 'quel est ton'), 
150 : ('peux-tu me donner ton' , 'quel est ton'), 
151 : ('peux tu me donner ton' , 'quel est ton'), 
152 : ('puis-je avoir ta' , 'quel est ta'), 
153 : ('puis je avoir ta' , 'quel est ta'), 
154 : ('peux-tu me donner ta' , 'quel est ta'), 
155 : ('peux tu me donner ta' , 'quel est ta'), 
156 : ('telephone' , 'téléphone'), 
157 : ('teléphone' , 'téléphone'), 
158 : ('télephone' , 'téléphone'), 
159 : ('Génésis' , 'Genesis'), 
160 : ('Genésis' , 'Genesis'), 
161 : ('Génesis' , 'Genesis'), 
162 : ('nous sommes en' , 'on est en'), 
163 : ('nous nous sommes' , 'on s\'est'), 
164 : ('emotion' , 'émotion'), 
165 : ('dis moi' , 'dis-moi'), 
166 : ('dit moi' , 'dis-moi'), 
167 : ('dit-moi' , 'dis-moi'), 
168 : ('pêter' , 'péter'), 
169 : ('parles tu' , 'parles-tu'), 
170 : ('parle tu' , 'parles-tu'), 
171 : ('parle-tu' , 'parles-tu'), 
172 : ('interroge moi' , 'interroge-moi'), 
173 : ('tu parler' , 'tu parlXXerXX'), 
174 : ('tu parle' , 'tu parles'), 
175 : ('tu parlXXerXX' , 'tu parler'), 
176 : ('tu m\'etonnes' , 'tu m\'étonnes'), 
177 : ('esquive' , 'évite'), 
178 : ('elude' , 'évite'), 
179 : ('élude' , 'évite'), 
180 : ('parles-moi' , 'parle-moi'), 
181 : ('parles moi' , 'parle-moi'), 
182 : ('parle moi' , 'parle-moi'), 
183 : ('de quelle facon' , 'de quelle façon'), 
184 : ('tu ressemble' , 'tu ressembles'), 
185 : ('prefere' , 'préfère'), 
186 : ('préfere' , 'préfère'), 
187 : ('prefère' , 'préfère'), 
188 : ('rappele' , 'rappelle'), 
189 : ('rapelle' , 'rappelle'), 
190 : ('rapele' , 'rappelle'), 
191 : ('c\'est évident' , 'c\'est sûr'), 
192 : ('pas tes oignons' , 'pas ton problème'), 
193 : ('pas ton probleme' , 'pas ton problème'), 
194 : ('ça te regarde pas' , 'ça ne te regarde pas'), 
195 : ('ca ne te regarde' , 'ça ne te regarde pas'), 
196 : ('ca te regardes pas' , 'ça ne te regarde pas'), 
197 : ('ca ne te regardes pas' , 'ça ne te regarde pas'), 
198 : ('ca m\'etonnerai' , 'ça m\'étonnerai'), 
199 : ('ça m\'etonnerai' , 'ça m\'étonnerai'), 
200 : ('ça m\'etonnerai' , 'ça m\'étonnerai'), 
201 : ('ca m\'etonnerai' , 'ça m\'étonnerai'), 
202 : ('chomage' , 'chômage'), 
203 : ('chomeur' , 'chômeur'), 
204 : ('puis je' , 'puis-je'), 
205 : ('deja' , 'déjà'), 
206 : ('déja' , 'déjà'), 
207 : ('dejà' , 'déjà'), 
208 : ('un bot' , 'un robot'), 
209 : ('chatbot' , 'chatterbot'), 
210 : ('malheureux' , 'triste'), 
211 : ('ca te gène de' , 'ça te gène de'), 
212 : ('ca te gene de' , 'ça te gène de'), 
213 : ('ca te dérange de' , 'ça te gène de'), 
214 : ('ca te derange de' , 'ça te gène de'), 
215 : ('je suis crevé' , 'je suis fatigué'), 
216 : ('je peut' , 'je peux'), 
217 : ('tu me saoule' , 'tu me soule'), 
218 : ('tu es saoulant' , 'tu es chiant'), 
219 : ('tu es soulant' , 'tu es chiant'), 
220 : ('tu saoul' , 'tu soul'), 
221 : ('putin' , 'putain'), 
222 : ('la forme?' , 'ça va ?'), 
223 : ('la forme ?' , 'ça va ?'), 
224 : ('tu sers a rien' , 'tu ne sers à rien'), 
225 : ('tu sers à rien' , 'tu ne sers à rien'), 
226 : ('tu sert a rien' , 'tu ne sers à rien'), 
227 : ('tu sert à rien' , 'tu ne sers à rien'), 
228 : ('tu ne sert a rien' , 'tu ne sers à rien'), 
229 : ('tu ne sert à rien' , 'tu ne sers à rien'), 
230 : (' etre' , ' être'), 
231 : ('\'etre' , '\'être'), 
232 : ('que fait tu' , 'que fais-tu'), 
233 : ('tu marches pas' , 'tu ne marches pas'), 
234 : ('tu marche pas' , 'tu ne marches pas'), 
235 : ('tu ne marche ' , 'tu ne marches'), 
236 : ('tu ne fonctionne pas' , 'tu ne marches pas'), 
237 : ('tu ne fonctionnes pas' , 'tu ne marches pas'), 
238 : ('tu fonctionne pas' , 'tu ne marches pas'), 
239 : ('tu fonctionnes pas' , 'tu ne marches pas'), 
240 : ('tu marches mal' , 'tu ne marches pas'), 
241 : ('tu marche mal' , 'tu ne marches pas'), 
242 : ('tu fonctionne mal' , 'tu ne marches pas'), 
243 : ('tu fonctionnes mal' , 'tu ne marches pas'), 
244 : ('tu marche bien' , 'tu marches bien'), 
245 : ('tu fonctionne bien' , 'tu marches bien'), 
246 : ('tu fonctionnes bien' , 'tu marches bien'), 
247 : ('de quoi parle t-on' , 'de quoi on parle'), 
248 : ('donne moi' , 'donne-moi'), 
249 : ('parcequ' , 'parce qu'), 
250 : ('Parce-qu' , 'Parce qu'), 
251 : ('tu as envie de' , 'tu veux'), 
252 : ('as-tu envie de' , 'veux-tu'), 
253 : ('ecoute' , 'écoute'), 
254 : ('diplome' , 'diplôme'), 
255 : ('de quelque chose d\'autre' , 'd\'autre chose'), 
256 : ('probleme' , 'problème'), 
257 : ('problême' , 'problème'), 
258 : ('addresse' , 'adresse'), 
259 : (' a jour' , ' à jour'), 
260 : ('bientot' , 'bientôt'), 
261 : ('gateau' , 'gâteau'), 
262 : ('pose moi' , 'pose-moi'), 
263 : ('1,' , '1.'), 
264 : ('2,' , '2.'), 
265 : ('3,' , '3.'), 
266 : ('4,' , '4.'), 
267 : ('5,' , '5.'), 
268 : ('6,' , '6.'), 
269 : ('7,' , '7.'), 
270 : ('8,' , '8.'), 
271 : ('9,' , '9.'), 
272 : ('la robe du cheval' , 'la couleur du cheval'), 
273 : ('appetit' , 'appétit'), 
274 : ('interressant' , 'intéressant'), 
275 : ('interessant' , 'intéressant'), 
276 : ('intérressant' , 'intéressant'), 
277 : ('combien est-ce que tu as' , 'combien as-tu'), 
278 : ('combien est ce que tu as' , 'combien as-tu'), 
279 : ('comme ca' , 'comme ça'), 
280 : (' raport' , ' rapport'), 
281 : ('proffession' , 'profession'), 
282 : ('réelement' , 'réellement'), 
283 : ('reelement' , 'réellement'), 
284 : ('reellement' , 'réellement'), 
285 : ('essayer de' , 'tenter de'), 
286 : ('tâcher de' , 'tenter de'), 
287 : ('degage' , 'dégage'), 
288 : ('tire toi' , 'va-t\'en'), 
289 : ('va t\'en' , 'va-t\'en'), 
290 : ('va-t-en' , 'va-t\'en'), 
291 : ('barre-toi' , 'va-t\'en'), 
292 : ('barre toi' , 'va-t\'en'), 
293 : ('arrete' , 'arrête'), 
294 : ('deconner' , 'déconner'), 
295 : ('deconer' , 'déconner'), 
296 : ('déconer' , 'déconner'), 
297 : ('je rigole' , 'je blague'), 
298 : ('heureux de te connaitre' , 'ravi de te connaître'), 
299 : ('heureuse de te connaitre' , 'ravi de te connaître'), 
300 : ('ravi de te connaitre' , 'ravi de te connaître'), 
301 : ('ravie de te connaitre' , 'ravi de te connaître'), 
302 : ('je plaisante' , 'je blague'), 
303 : ('t\'en fais pas' , 't\'inquiète pas'), 
304 : ('t\'en fait pas' , 't\'inquiète pas'), 
305 : ('t\'inquiètes pas' , 't\'inquiète pas'), 
306 : ('rappelle moi' , 'rappelle-moi'), 
307 : ('rappelles moi' , 'rappelle-moi'), 
308 : ('rappelles-moi' , 'rappelle-moi'), 
309 : ('meteo' , 'météo'), 
310 : ('méteo' , 'météo'), 
311 : ('metéo' , 'météo'), 
312 : ('merdique' , 'de merde'), 
313 : ('emerde' , 'emmerde'), 
314 : ('je me fait' , 'je me fais'), 
315 : ('etait' , 'était'), 
316 : ('etais' , 'étais'), 
317 : ('écoute' , 'écoute'), 
318 : ('t\'existe' , 'tu existe'), 
319 : ('tu fais la tête' , 'tu fais la gueule'), 
320 : ('tu boudes' , 'tu fais la gueule'), 
321 : (' véxé' , ' vexé'), 
322 : ('tu es vexé' , 'tu fais la gueule'), 
323 : ('boudes-tu' , 'fais-tu la gueule'), 
324 : ('fais-tu la tête' , 'fais-tu la gueule'), 
325 : ('es-tu vexé' , 'fais-tu la gueule'), 
326 : ('Nouvelle-Zelande' , 'Nouvelle-Zélande'), 
327 : ('Nouvelle Zelande' , 'Nouvelle-Zélande'), 
328 : ('Nouvelle Zélande' , 'Nouvelle-Zélande'), 
329 : ('a-t\'il' , 'a-t-il'), 
330 : ('a t\'il' , 'a-t-il'), 
331 : ('à coté' , 'à côté'), 
332 : ('a coté' , 'à côté'), 
333 : ('s\'il te plaît' , 's\'il te plait'), 
334 : ('t\'en a pas' , 'tu n\'en a pas'), 
335 : ('tu en a pas' , 'tu n\'en a pas'), 
336 : ('discuter' , 'converser'), 
337 : ('soucis' , 'problèmes'), 
338 : (' rève' , ' rêve'), 
339 : ('celle là' , 'celle-là'), 
340 : ('celui là' , 'celui-là'), 
341 : ('m\'en fou' , 'm\'en fiche'), 
342 : ('m\'en branle' , 'm\'en fiche'), 
343 : ('m\'en bat les ' , 'm\'en fiche'), 
344 : ('ou se trouve' , 'où se trouve'), 
345 : ('est ce que' , 'est-ce que'), 
346 : ('pourrais-tu' , 'peux-tu'), 
347 : ('pourrais tu' , 'peux-tu'), 
348 : ('tu pourrais' , 'tu peux'), 
349 : ('accepterais-tu' , 'acceptes-tu'), 
350 : ('accepterais tu' , 'acceptes-tu'), 
351 : ('tu accepterais' , 'tu acceptes'), 
352 : ('voudrais tu' , 'veux-tu'), 
353 : ('voudrais-tu' , 'veux-tu'), 
354 : ('tu voudrais' , 'tu veux'), 
355 : ('aimerais-tu' , 'veux-tu'), 
356 : ('aimerais tu' , 'veux-tu'), 
357 : ('tu aimerais' , 'tu veux'), 
358 : ('es-tu capable de' , 'peux-tu'), 
359 : ('tu es capable de' , 'tu peux'), 
360 : (' createur' , ' créateur'), 
361 : ('paumé' , 'perdu'), 
362 : ('pas gentil' , 'méchant'), 
363 : ('vilain' , 'méchant'), 
364 : ('depression' , 'dépression'), 
365 : ('deprime' , 'déprime'), 
366 : ('jeux vidéo' , 'jeux-vidéo'), 
367 : ('jeux-video' , 'jeux-vidéo'), 
368 : ('jeu video' , 'jeux-vidéo'), 
369 : ('on fais' , 'on fait'), 
370 : ('tout a l\'heure' , 'tout à l\'heure'), 
371 : (' bete' , ' bête'), 
372 : (' bète' , ' bête'), 
373 : (' béte' , ' bête'), 
374 : ('tu connait' , 'tu connais'), 
375 : ('pas fut-fut' , 'idiot'), 
376 : ('pas futé' , 'idiot'), 
377 : ('pas intelligent' , 'idiot'), 
378 : ('pas malin' , 'idiot'), 
379 : ('pas très intelligent' , 'idiot'), 
380 : ('stupide' , 'idiot'), 
381 : ('c\'est a dire' , 'c\'est à dire'), 
382 : ('reponse' , 'réponse'), 
383 : ('ce n\'est pas' , 'c\'est pas'), 
384 : ('prends tu' , 'prends-tu'), 
385 : ('d\'ou' , 'd\'où'), 
386 : ('vraiment rien' , 'rien'), 
387 : ('petit frère' , 'frère'), 
388 : ('grand frère' , 'frère'), 
389 : ('petite soeur' , 'soeur'), 
390 : ('grande soeur' , 'soeur'), 
391 : ('joindre' , 'contacter'), 
392 : ('frere' , 'frère'), 
393 : ('desire' , 'désire'),
394 : (' + ','+'),
395 : (' - ','-'),
396 : ('vas-y', 'vas y'),
397 : ('maybe', 'peut-être')
}